---
- name: create a network
  tags: ['network', 'instances','bastion']
  gcp_compute_network:
   name: "{{ network_name_default }}"
   project: "{{ gcp_project }}"
   auth_kind: "{{ gcp_auth_kind }}"
   service_account_file: "{{ gcp_service_account_file }}"
   scopes:
     - "{{ scope_compute }}"
   state: present
  register: network

- name: create an address
  tags: ['ext-addr']
  gcp_compute_address:
   name: '{{ name_address }}-{{ item }}-lb'
   region: "{{ gcp_region }}"
   project: "{{ gcp_project }}"
   auth_kind: "{{ gcp_auth_kind }}"
   service_account_file: "{{ gcp_service_account_file }}"
   address_type: EXTERNAL
   scopes:
   - "{{ scope_compute }}"
   state: present
  register: address
  loop: "{{ address_types }}"

- name: create a disk
  tags: ['instances', 'disks']
  gcp_compute_disk:
    name: '{{ name_disk }}-{{ sequence }}'
    size_gb: "{{ disk_size }}"
    source_image: '{{ disk_source_image }}'
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_service_account_file }}"
    scopes:
    - "{{ scope_compute }}"
    state: present
  register: disk

- name: create an instance
  tags: ['instances']
  gcp_compute_instance:
    name: "{{ name_instance }}-{{ sequence }}"
    state: present
    machine_type: "{{ machine_type }}"
    disks:
    - auto_delete: true
      boot: true
      source: "{{ disk }}"
    network_interfaces:
    - network: "{{ network }}"
      access_configs:
      - name: 'External NAT'
        type: 'ONE_TO_ONE_NAT'
        nat_ip: "{{ address }}"
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_service_account_file }}"
    tags:
      items:
      - delete-apigee-instance-firewall
    metadata:
       'startup-script': 'rm -f /etc/sudoers.d/remove-requiretty && echo \"Defaults !requiretty\" >> /etc/sudoers.d/remove-requiretty'
    scopes:
    - "{{ scope_compute }}"
  register: instance


