---
- name: Create infrastructure
  hosts: localhost

  vars:
    project_path: 'dev'
    gcp_credentials_file: "{{ '~/.apigee-secure/fedex-pilot/fedex-pilot-apigee-service-account.json' | expanduser }}"
    service_account_email: "apigee@fedex-pilot.iam.gserviceaccount.com"
    gcp_project_name: 'fedex-pilot'
    terraform_version: "0.12.0"
    terraform_download_links:
      Debian: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
      MacOSX: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_darwin_amd64.zip"
    regions:
    - {
        region: "us-east1",
        apigee_region: "dc-1",
        zone: "us-east1-b",
        ms_name: "planet-dc-1-ms-dc-1-ldap-dc-1-ui",
        ms_count: 1,
        ds_name: "planet-dc-1-ds",
        ds_count: 9,
        rmp_name: "planet-dc-1-rmp",
        rmp_count: 24,
        qpid_name: "planet-dc-1-qpid",
        qpid_count: 6,
        pg_only_name: "planet-dc-1-pg",
        pg_only_count: 0,
        pgmaster_name: "planet-dc-1-pg-dc-1-pgmaster",
        pgmaster_count: 1,
        pgstandby_name: "planet-dc-2-pg-dc-2-pgstandby",
        pgstandby_count: 0,
        dev_portal_name: "planet-dc-1-dp-ui-dc-1-dp-db",
        dev_portal_count: 0
    }
#    - {
#        region: "us-east1",
#        apigee_region: "dc-2",
#        zone: "us-east1-c",
#        ms_name: "planet-dc-2-ms-dc-2-ldap-dc-2-ui",
#        ms_count: 1,
#        ds_name: "planet-dc-2-ds",
#        ds_count: 9,
#        rmp_name: "planet-dc-2-rmp",
#        rmp_count: 24,
#        qpid_name: "planet-dc-2-qpid",
#        qpid_count: 6,
#        pg_only_name: "planet-dc-2-pg",
#        pg_only_count: 0,
#        pgmaster_name: "planet-dc-2-pg-dc-2-pgmaster",
#        pgmaster_count: 0,
#        pgstandby_name: "planet-dc-2-pg-dc-2-pgstandby",
#        pgstandby_count: 1,
#        dev_portal_name: "planet-dc-2-dp-ui-dc-2-dp-db",
#        dev_portal_count: 0
#    }
#    - {
#        region: "us-east1",
#        apigee_region: "dc-3",
#        zone: "us-east1-d",
#        ms_name: "planet-dc-3-ms-dc-3-ldap-dc-3-ui",
#        ms_count: 0,
#        ds_name: "planet-dc-3-ds",
#        ds_count: 9,
#        rmp_name: "planet-dc-3-rmp",
#        rmp_count: 24,
#        qpid_name: "planet-dc-3-qpid",
#        qpid_count: 6,
#        pg_only_name: "planet-dc-3-pg",
#        pg_only_count: 0,
#        pgmaster_name: "planet-dc-3-pg-dc-3-pgmaster",
#        pgmaster_count: 0,
#        pgstandby_name: "planet-dc-3-pg-dc-3-pgstandby",
#        pgstandby_count: 0,
#        dev_portal_name: "planet-dc-3-dp-ui-dc-3-dp-db",
#        dev_portal_count: 0
#    }

  tasks:
    - name: Install archive management packages
      become: true
      tags: ['system']
      apt:
        name: "unzip"
        state: present
      when: ansible_distribution == "Debian"

    - name: Install archive management packages on Mac
      tags: ['system']
      package:
        name: "unzip"
        state: present
      when: ansible_distribution == "MacOSX"

    - name: Install archive management packages
      become: true
      tags: ['system']
      package:
        name: "unzip"
        state: present
      when: ansible_distribution != "MacOSX"

    - name: Set terraform link
      set_fact:
        terraform_download_link: "{{ terraform_download_links[ansible_distribution] }}"

    - name: Download Terraform binary
      get_url:
        url: "{{ terraform_download_link }}"
        dest: "./{{ terraform_download_link | basename }}"
        validate_certs: no

    - name: Unarchive terraform binary
      unarchive:
        src: "{{ terraform_download_link | basename }}"
        dest: ./
        remote_src: yes

    - name: Create infrastructure
      terraform:
        binary_path: "{{ playbook_dir }}/terraform"
        project_path: "{{ playbook_dir }}/modules/infrastructure"
        state: present
        force_init: yes
        variables:
          region: "{{ item.region }}"
          zone: "{{ item.zone }}"
          credentials_file: "{{ gcp_credentials_file }}"
          gcp_project_name: "{{ gcp_project_name }}"
          service_account_email: "{{ service_account_email }}"
          ms_name: "{{ item.ms_name }}"
          ms_count: "{{ item.ms_count }}"
          ds_name: "{{ item.ds_name }}"
          ds_count: "{{ item.ds_count }}"
          rmp_name: "{{ item.rmp_name }}"
          rmp_count: "{{ item.rmp_count }}"
          qpid_name: "{{ item.qpid_name }}"
          qpid_count: "{{ item.qpid_count }}"
          pg_only_name: "{{ item.pg_only_name }}"
          pg_only_count: "{{ item.pg_only_count }}"
          pgmaster_name: "{{ item.pgmaster_name }}"
          pgmaster_count: "{{ item.pgmaster_count }}"
          pgstandby_name: "{{ item.pgstandby_name }}"
          pgstandby_count: "{{ item.pgstandby_count }}"
          dev_portal_name: "{{ item.dev_portal_name }}"
          dev_portal_count: "{{ item.dev_portal_count }}"
      with_items: "{{ regions }}"

    - name: Create topology
      terraform:
        binary_path: "{{ playbook_dir }}/terraform"
        project_path: "{{ playbook_dir }}/{{ item.apigee_region }}"
        state: present
        force_init: yes
        variables:
          region: "{{ item.region }}"
          zone: "{{ item.zone }}"
          credentials_file: "{{ gcp_credentials_file }}"
          gcp_project_name: "{{ gcp_project_name }}"
          service_account_email: "{{ service_account_email }}"
          ms_name: "{{ item.ms_name }}"
          ms_count: "{{ item.ms_count }}"
          ds_name: "{{ item.ds_name }}"
          ds_count: "{{ item.ds_count }}"
          rmp_name: "{{ item.rmp_name }}"
          rmp_count: "{{ item.rmp_count }}"
          qpid_name: "{{ item.qpid_name }}"
          qpid_count: "{{ item.qpid_count }}"
          pg_only_name: "{{ item.pg_only_name }}"
          pg_only_count: "{{ item.pg_only_count }}"
          pgmaster_name: "{{ item.pgmaster_name }}"
          pgmaster_count: "{{ item.pgmaster_count }}"
          pgstandby_name: "{{ item.pgstandby_name }}"
          pgstandby_count: "{{ item.pgstandby_count }}"
          dev_portal_name: "{{ item.dev_portal_name }}"
          dev_portal_count: "{{ item.dev_portal_count }}"
      with_items: "{{ regions }}"
