---
- name: Create infrastructure
  hosts: localhost
  vars:
    project_path: "5-node"

  tasks:
    - name: Destroy infrastructure
      terraform:
        binary_path: "{{ playbook_dir }}/terraform"
        project_path: "{{ playbook_dir }}/{{ project_path }}"
        force_init: true
        state: absent