---
- name: Create infrastructure
  hosts: localhost
  vars:
    project_path: "5-node"
    terraform_version: "0.12.0"
    terraform_download_links:
      Debian: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
      MacOSX: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_darwin_amd64.zip"

  tasks:
    - name: Install archive managment packages
      package:
        name: "unzip"
        state: present

    - name: Set terraform link
      set_fact:
        terraform_download_link: "{{ terraform_download_links[ansible_distribution] }}"

    - name: Download Terraform binary
      get_url:
        url: "{{ terraform_download_link }}"
        dest: "./{{ terraform_download_link | basename }}"

    - name: Unarchive terraform binary
      unarchive:
        src: "{{ terraform_download_link | basename }}"
        dest: ./
        remote_src: yes

    - name: Create infrastructure
      terraform:
        binary_path: "{{ playbook_dir }}/terraform"
        project_path: "{{ playbook_dir }}/{{ project_path }}"
        force_init: true
        state: present