---
- name: Create infrastructure
  hosts: localhost
  vars_prompt:
    - name: project_path
      prompt: "Which project do you want to build? ['5-node','aio','dev','prod']"
      default: "5-node"
      private: no

    - name: gcp_credentials_file
      prompt: "Service Account Credentials File Path"
      default: "{{ '~/.apigee-secure/sandbox-1f5fb288d552.json' | expanduser }}"
      private: no

    - name: gcp_project_name
      prompt: "GCP Project Name"
      default: "sandbox-173316"
      private: no

  vars:
    terraform_state_file: "{{ playbook_dir }}/terraform.tfstate"
    terraform_workspace: "{{ playbook_dir }}"

  tasks:
    - name: Destroy infrastructure
      terraform:
        binary_path: "{{ playbook_dir }}/terraform"
        project_path: "{{ playbook_dir }}/{{ project_path }}"
        state: absent
        purge_workspace: yes
#        state_file: "{{ terraform_state_file }}"
#        plan_file: "{{ terraform_state_file }}"
#        workspace: "{{ terraform_workspace }}"
        variables:
          region: "{{ default_region }}"
          zone: "{{ default_zone }}"
          credentials_file: "{{ gcp_credentials_file }}"
          gcp_project_name: "{{ gcp_project_name }}"
