---
- name: Destroy infrastructure
  hosts: localhost

#  vars_files:
#    - gce-attributes.yml

  tasks:
    - name: Destroy infrastructure
      terraform:
        binary_path: "{{ playbook_dir }}/terraform"
        project_path: "{{ playbook_dir }}/{{ project_path }}"
        state: absent
        force_init: yes
        purge_workspace: yes
        variables:
          credentials_file: "{{ gcp_credentials_file }}"
          gcp_project_name: "{{ gcp_project_name }}"
          service_account_email: "{{ service_account_email }}"
          dev_portal_name: "{{ dev_portal_name }}"
          dev_portal_count: "{{ dev_portal_count }}"
          dev_portal_instance_type: "{{ dev_portal_instance_type }}"
          dc_1_gcp_region: "{{ dc_1_gcp_region }}"
          dc_1_zone: "{{ dc_1_zone}}"
          dc_1_region: "{{ dc_1_region }}"
          dc_1_ms_name: "{{ dc_1_ms_name }}"
          dc_1_ms_count: "{{ dc_1_ms_count }}"
          dc_1_ms_instance_type: "{{ dc_1_ms_instance_type }}"
          dc_1_ms_disk_size: "{{ dc_1_ms_disk_size }}"
          dc_1_ds_name: "{{ dc_1_ds_name }}"
          dc_1_ds_count: "{{ dc_1_ds_count }}"
          dc_1_ds_instance_type: "{{ dc_1_ds_instance_type }}"
          dc_1_ds_disk_size: "{{ dc_1_ds_disk_size }}"
          dc_1_rmp_name: "{{ dc_1_rmp_name }}"
          dc_1_rmp_count: "{{ dc_1_rmp_count }}"
          dc_1_rmp_instance_type: "{{ dc_1_rmp_instance_type }}"
          dc_1_rmp_disk_size: "{{ dc_1_rmp_disk_size }}"
          dc_1_qpid_name: "{{ dc_1_qpid_name }}"
          dc_1_qpid_count: "{{ dc_1_qpid_count }}"
          dc_1_qpid_instance_type: "{{ dc_1_qpid_instance_type }}"
          dc_1_qpid_disk_size: "{{ dc_1_qpid_disk_size }}"
          pg_only_name: "{{ pg_only_name }}"
          pg_only_count: "{{ pg_only_count }}"
          pg_only_instance_type: "{{ pg_only_instance_type }}"
          pg_only_disk_size: "{{ pg_only_disk_size }}"
          dc_1_pgmaster_name: "{{ dc_1_pgmaster_name }}"
          dc_1_pgmaster_count: "{{ dc_1_pgmaster_count }}"
          dc_1_pgmaster_instance_type: "{{ dc_1_pgmaster_instance_type }}"
          dc_1_pgmaster_disk_size: "{{ dc_1_pgmaster_disk_size }}"
          dc_1_pgstandby_name: "{{ dc_1_pgstandby_name }}"
          dc_1_pgstandby_count: "{{ dc_1_pgstandby_count}}"
          dc_1_pgstandby_instance_type: "{{ dc_1_pgstandby_instance_type }}"
          dc_1_pgstandby_disk_size: "{{ dc_1_pgstandby_disk_size }}"
          dc_2_region: "{{ dc_2_region }}"
          dc_2_gcp_region: "{{ dc_2_gcp_region }}"
          dc_2_zone: "{{ dc_2_zone }}"
          dc_2_ms_name: "{{ dc_2_ms_name }}"
          dc_2_ms_count: "{{ dc_2_ms_count }}"
          dc_2_ms_instance_type: "{{ dc_2_ms_instance_type }}"
          dc_2_ms_disk_size: "{{ dc_2_ms_disk_size }}"
          dc_2_ds_name: "{{ dc_2_ds_name }}"
          dc_2_ds_count: "{{ dc_2_ds_count }}"
          dc_2_ds_instance_type: "{{ dc_2_ds_instance_type }}"
          dc_2_ds_disk_size: "{{ dc_2_ds_disk_size }}"
          dc_2_rmp_name: "{{ dc_2_rmp_name }}"
          dc_2_rmp_count: "{{ dc_2_rmp_count }}"
          dc_2_rmp_instance_type: "{{ dc_2_rmp_instance_type }}"
          dc_2_rmp_disk_size: "{{ dc_2_rmp_disk_size }}"
          dc_2_qpid_name: "{{ dc_2_qpid_name }}"
          dc_2_qpid_count: "{{ dc_2_qpid_count }}"
          dc_2_qpid_instance_type: "{{ dc_2_qpid_instance_type }}"
          dc_2_qpid_disk_size: "{{ dc_2_qpid_disk_size }}"
          dc_2_pgmaster_name: "{{ dc_2_pgmaster_name }}"
          dc_2_pgmaster_count: "{{ dc_2_pgmaster_count }}"
          dc_2_pgmaster_instance_type: "{{ dc_2_pgmaster_instance_type }}"
          dc_2_pgmaster_disk_size: "{{ dc_2_pgmaster_disk_size }}"
          dc_2_pgstandby_name: "{{ dc_2_pgstandby_name }}"
          dc_2_pgstandby_count: "{{ dc_2_pgstandby_count }}"
          dc_2_pgstandby_instance_type: "{{ dc_2_pgstandby_instance_type }}"
          dc_2_pgstandby_disk_size: "{{ dc_2_pgstandby_disk_size }}"
          dc_3_region: "{{ dc_3_region }}"
          dc_3_gcp_region: "{{ dc_3_gcp_region }}"
          dc_3_zone: "{{ dc_3_zone }}"
          dc_3_ds_name: "{{ dc_3_ds_name }}"
          dc_3_ds_count: "{{ dc_3_ds_count }}"
          dc_3_ds_instance_type: "{{ dc_3_ds_instance_type }}"
          dc_3_ds_disk_size: "{{ dc_3_ds_disk_size }}"
          dc_3_rmp_name: "{{ dc_3_rmp_name }}"
          dc_3_rmp_count: "{{ dc_3_rmp_count }}"
          dc_3_rmp_instance_type: "{{ dc_3_rmp_instance_type }}"
          dc_3_rmp_disk_size: "{{ dc_3_rmp_disk_size }}"
          dc_3_qpid_name: "{{ dc_3_qpid_name }}"
          dc_3_qpid_count: "{{ dc_3_qpid_count }}"
          dc_3_qpid_instance_type: "{{ dc_3_qpid_instance_type }}"
          dc_3_qpid_disk_size: "{{ dc_3_qpid_disk_size }}"
