---
- name: Setup the controller workspace
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
  - "{{ setup_properties | default('setup-resources/setup-properties.yml') }}"

  tasks:
  - name: Clean all folders
    tags: ['clean']
    file:
      path: "{{ item }}"
      state: absent
    with_items:
    - "{{ target_ansible_workspace }}"
    - ansible.cfg

  - name: Recreate folders
    file:
      path: '{{ item }}'
      state: directory
    with_items: "{{ setup_dirs }}"

  - name: Setting up Ansible in this directory
    file:
      path: "{{ item }}"
      state: directory
    with_items:
    - "{{ setup_dirs }}"
    - "{{ playbook_dir }}/inventory"

  - name: Check for remote user name
    assert:
      that:
        - username is defined
      msg: "Please provide the remote user name: -e username=<username>"

  - name: create ansible.cfg file from template
    template:
      src: "{{ setup_resources }}/templates/ansible.cfg.j2"
      dest: ansible.cfg
      backup: yes
      force: yes

  - name: Set ANSIBLE_CONFIG
    set_fact:
      ansible_config_file: ansible.cfg

  - name: Create starter template folders
    file:
      path: "{{ item.dest_path }}"
      state: directory
    with_items: "{{ starter_templates }}"

  - name: Copy Starter Template Files
    copy:
      src: "{{ item.src_path }}/{{ item.file_name }}"
      dest: "{{ item.dest_path }}/{{ item.file_name }}"
    with_items: "{{ starter_templates }}"

  - name: Determine that state of inventory folder
    stat:
      path: inventory
    register: inventory_state

  - name: Assert that inventory folder exists
    assert:
      that:
      - inventory_state.stat.exists
      msg: "Please create an inventory folder and place your inventory definitions there"
