---
- name: Setup Accelerator Offline
  hosts: localhost
  vars:
    # Use this endpoint to clone github.com using HTTPS
    repository_secure_endpoint_https: "https://github.com/carlosfrias"
    repo_name: "apigee-opdk-playbook-setup-ansible"
    archive_target_folder_name: apigee-opdk-accelerator
    archive_folder: "{{ playbook_dir }}/{{ archive_target_folder_name }}"
    playbook_requirements_path:
      - "../../installations/multi-node/requirements.yml"
      - "../../installations/devportal/requirements.yml"
      - "../../installations/mirror/requirements.yml"
    folder_list_to_archive:
      - "~/.ansible"
      - "~/.apigee"
      - "~/.apigee-secure"

  tasks:
    - name: Create Archive folder
      file:
        path: "{{ archive_folder }}"
        state: directory

    - name: Download Ansible OPDK Accelerator
      git:
        repo: "{{ repository_secure_endpoint_https }}/{{ repo_name }}"
        dest: "{{ archive_folder }}/{{ repo_name }}"
        accept_hostkey: yes

    - name: Download Roles used by All Playbooks
      command: "ansible-galaxy install -r {{ item }} -f"
      with_items: "{{ playbook_requirements_path }}"

    - name: Verify that rsync is installed
      become: true
      package:
        name: "rsync"
        state: present

    - name: Synchronize Folder List to Archive
      synchronize:
        src: "{{ item }}"
        dest: "{{ archive_folder }}"
      with_items: "{{ folder_list_to_archive }}"

    - name: Create an Ansible OPDK Accelerator Archive
      archive:
        dest: "{{ archive_folder }}.tar.gz"
        path: "{{ archive_folder }}"
        format: gz

    - name: Verify that gtar is installed on Target Host
      become: true
      package:
        name: gtar
        state: present
      delegate_to: "{{ target_hosts }}"

    - name: Transfer Ansible OPDK Accelerator Archive to Target Host
      become: true
      unarchive:
        dest: "/tmp"
        src: "{{ archive_folder }}.tar.gz"
      delegate_to: "{{ target_hosts }}"

    - name: Verify that rsync is installed on Target Host
      become: true
      package:
        name: "rsync"
        state: present
      delegate_to: "{{ target_hosts }}"

    - name: Move folder list to User Home on Target Host
      become: true
      synchronize:
        src: "/tmp/{{ archive_target_folder_name }}/{{ item }}"
        dest: "~/{{ item }}"
        dirs: yes
        verify_host: no
        set_remote_user: no
        use_ssh_args: no
        rsync_opts:
          - "--remove-source-files"
      delegate_to: "{{ target_hosts }}"
      with_items:
          - ".ansible"
          - ".apigee"
          - ".apigee-secure"



