---
- name: Validate Routers & Message Processors
  hosts: rmp,r
  tags: ['validate']
  serial: 1
  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - { role: apigee-opdk-modules, tags: ['validate', 'validate-cleanup','validate-setup'] }
    - { role: apigee-opdk-settings-private-address, tags: ['validate', 'validate-cleanup']  }
    - { role: apigee-opdk-settings-region, tags: ['validate', 'validate-cleanup']  }
    - { role: apigee-opdk-setup-validate, tags: ['validate-setup'] }
    - { role: apigee-opdk-setup-validate-cleanup, tags: ['validate-cleanup'] }
