---
- name: Validate that port requirements are met
  hosts: ms
  vars:
    test_port: 1234
    ports: "{{ ms_ports }}"
  vars_files:
  -  port-list.yml

#  roles:
#    - { role: apigee-opdk-module }

  tasks:
  - name: Loop through ports
    include_tasks: listener_client.yml
    with_items: groups['ds']
    loop_control:
      loop_var: host
