---
- name: Update cache
  hosts: planet
  tags: ['cache']
  strategy: free
  roles:
  - { role: apigee-opdk-settings-private-address }
  - { role: apigee-opdk-settings-region }
  - { role: apigee-opdk-settings-management-server }
  - { role: apigee-opdk-settings-cassandra }
  - { role: apigee-opdk-settings-ldap }
  - { role: apigee-opdk-settings-postgres }

- name: Validate that port requirements are met
  hosts: ms
  tags: ['ms']
  strategy: free
  vars:
    ports: "{{ ms_ports }}"
  vars_files:
  -  port-list.yml

  roles:
    - { role: apigee-opdk-port-check, host_list: "{{ groups['ds'] }}" }
    - { role: apigee-opdk-port-check, host_list: "{{ groups['rmp'] }}" }
    - { role: apigee-opdk-port-check, host_list: "{{ groups['qpid'] }}" }
    - { role: apigee-opdk-port-check, host_list: "{{ groups['pg'] }}" }
    - { role: apigee-opdk-port-check, host_list: "{{ groups['ui'] }}" }
    - { role: apigee-opdk-port-check, host_list: "{{ groups['ldap'] }}" }

