---
- name: Collect information from user
  hosts: edge
  vars:
    property_folders:
    - "~/.apigee-secure"
    - "~/.apigee"

  vars_prompt:

    - name: "prompt_org_name"
      prompt: "Name of organization for these routers and message processors"
      private: no

    - name: "prompt_env_name"
      prompt: "Name of the environment to which to apply these routers and message processors"
      default: "test"
      private: no

    - name: "prompt_opdk_mp_pod"
      prompt: "Pod name that should be used for these routers and message processors"
      default: "gateway"
      private: no

    - name: "prompt_virtual_host_port"
      prompt: "Virtual host port number"
      default: "9001"
      private: no

    - name: "prompt_virtual_host_name"
      prompt: "Virtual host port name"
      default: "default"
      private: no

    - name: "prompt_load_balancer"
      prompt: "Space delimited string of router IP addresses or the load balancer for this set of routers"
      private: no


  roles:
  - { role: apigee-opdk-modules }

  tasks:
    - name: Update cache with provided values
      set_fact:
        cacheable: True
        org_name: "{{ prompt_org_name }}"
        env_name: "{{ prompt_env_name }}"
        opdk_mp_pod: "{{ prompt_opdk_mp_pod }}"
        virtual_host_port: "{{ prompt_virtual_host_port }}"
        virtual_host_name: "{{ prompt_virtual_host_name }}"
        load_balancer: "{{ prompt_load_balancer }}"

- name: Configure Organization and Environments
  hosts: ms[0]
  gather_facts: no
  tags: ['org']

  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
    tenants:
      - { org: "{{ org_name }}", env: "{{ env_name }}", new_user: 'n' }

  roles:
  - { role: apigee-opdk-modules, tags: ['config'] }
  - { role: apigee-opdk-setup-org-config, tags: ['config'] }
  - { role: apigee-opdk-setup-org, tags: ['setup'] }

- name: Configure Organization and Environments
  hosts: edge
  gather_facts: no
  tags: ['org']

  tasks:
    - name: Update cache with provided values
      set_fact:
        cacheable: True
        org_name: ""
        env_name: ""
        opdk_mp_pod: ""
        virtual_host_port: ""
        virtual_host_name: ""
        load_balancer: ""

