---
- name: Update Postgres Standby variables
  hosts: pgstandby
  roles:
    - { role: apigee-opdk-settings-private-address, tags: ['minimum', 'cache', 'ds', 'ms', 'rmp', 'r', 'mp', 'qpid', 'pg', 'pgmaster', 'pgstandby', 'org', 'validate', 'validate-cleanup']  }

- name: Add Postgres Standby servers beyond one
  hosts: pgmaster
  tasks:
    - name: Setup replication variable
      set_fact:
        replication_string: ''

    - name: Create
      set_fact:
        replication_string: "host     replication     apigee {{ hostvars[item]['private_address'] }}/32 trust\n"
      with_items: "{{ groups['pgstandby'] }}"

    - debug:
        var: replication_string
