---
- name: Create a team
  hosts: ms
  gather_facts: no
  vars:
    team_members:
      - joe@apigee.com
      - jane@apigee.com
      - example@apigee.com
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - { role: apigee-opdk-modules }
    - { role: apigee-opdk-settings-private-address, tags: ['minimum', 'cache', 'ds', 'ms', 'rmp', 'r', 'mp', 'qpid', 'pg', 'pgmaster', 'pgstandby', 'org', 'validate', 'validate-cleanup']  }
    - { role: apigee-opdk-settings-management-server, tags: ['minimum', 'cache', 'ds', 'ms', 'rmp', 'r', 'mp', 'qpid', 'pg', 'pgmaster', 'pgstandby', 'org', 'validate', 'validate-cleanup']  }
  tasks:
    - name: Create team on org
      uri:
        url: "http://{{ local_mgmt_ip }}:{{ ms_port }}/v1/o/{{ org_name }}/teams"
        method: "POST"
        user: "{{ opdk_user_email }}"
        password: "{{ opdk_user_pass }}"
        force_basic_auth: "yes"
        body_format: "json"
        body:
          name: "{{ org_name }}"
          displayName: "{{ org_name }}"
          teamMembers:
            - "{{ team_members }}"
