---
- name: Enable Teams on an org
  hosts: ms
  gather_facts: no
  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - { role: apigee-opdk-modules }

  tasks:
    - name: Enable teams on org
      uri:
        url: http://{{ mgmt_ip }}:8080/organizations/{{ org_name }}
        method: POST
        username: "{{ opdk_user_email }}"
        password: "{{ opdk_user_pass }}"
        body_format: json
        body:
          name: "{{ org_name }}"
          properties:
            property:
              name: features.isTeamsEnabled
              value: true

