---
- src: https://github.com/carlosfrias/apigee-opdk-start-components.git

- src: https://github.com/carlosfrias/apigee-opdk-stop-components.git

- src: https://github.com/carlosfrias/apigee-opdk-cwc-update.git

- src: https://github.com/carlosfrias/apigee-opdk-modules.git
