---
- name: Setup the Ansible controller
  hosts: "{{ target_host }}"
  vars:
    remote_user: friasc
    ansible_workspace: "~/apigee-workspace/ansible"
    apigee_workspace: "~/apigee-workspace/test-4-apigee"
    apigee_secure_folder: "~/apigee-workspace/test-3-apigee-secure"


  roles:
  - { role: apigee-opdk-setup-ansible-controller }
