---
- name: Setup the Ansible controller
  hosts: "{{ target_hosts }}"

  vars:
    remote_user: friasc
    ansible_workspace: "~/apigee-workspace"

  roles:
  - { role: apigee-opdk-setup-ansible-controller }
