---
- name: Setup the Ansible controller
  hosts: "{{ target_host }}"
  vars:
    remote_user: friasc
    ansible_workspace: "~/apigee-workspace/ansible"
    apigee_workspace: "~/apigee-workspace"
    apigee_secure_folder: "~/.apigee-secure"

  roles:
  - { role: apigee-opdk-setup-ansible-controller }
