---
- name: Setup the Ansible controller
  hosts: controller
  vars:
    ansible_workspace: "~/.ansible"
    apigee_workspace: "~/apigee-workspace"
    apigee_secure_folder: "~/.apigee-secure"
    apigee_custom_properties_folder: "~/.apigee"

  roles:
  - { role: apigee-opdk-setup-ansible-controller }
