---
- name: Setup the Ansible controller
  hosts: controller
  gather_facts: no
  vars:
    # This is the location in which Ansible files can be installed.
    # ansible_workspace: "~/.ansible"

    # This is the location where the playbook folder will be located.
    # apigee_workspace: "~/apigee-workspace"

    # This is the location where credentials, license material, GCP service account files, AWS key and secret, etc are stored"
    # apigee_secure_folder: "~/.apigee-secure"

    # This is the location of custom property files.
    # apigee_custom_properties_folder: "~/.apigee"
  vars_prompt:
    - name: ansible_workspace
      default: "~/.ansible"
      private: no
      prompt: "Please provide the path to the Ansible workspace"

    - name: apigee_workspace
      default: "~/apigee-workspace"
      private: no
      prompt: "Please provide the path to the Apigee playbook workspace"

    - name: apigee_secure_folder
      default: "~/.apigee-secure"
      private: no
      prompt: "Please provide the path to the folder that will contain credentials and other sensitive information"

    - name: apigee_custom_properties_folder
      default: "/.apigee"
      private: no
      prompt: "Please provide the path to the location of the customer_properties.yml"

  pre_tasks:
  - name: Load variables
    include_vars:
      dir: "{{ item | expanduser }}"
    with_items:
    - "{{ apigee_secure_folder }}"
    - "{{ apigee_custom_properties_folder }}"

  roles:
  - { role: apigee-opdk-setup-ansible-controller }

