---
- name: Download packages for manual installation
  hosts: "{{ target_hosts }}"
  gather_facts: no
  tags: ['download']
  vars:
    property_folders:
      - "~/.apigee"
  roles:
    - { role: apigee-opdk-modules }
  tasks:
    - name: Download yum packages
      become: true
      shell: "yum reinstall --downloadonly --downloaddir={{ local_apigee_path }} {{ archive_extra_packages | join(' ') }}"



- name: Upload downloaded packages to planet
  hosts: planet
  gather_facts: no
  tags: ['upload']
  vars:
    property_folders:
      - "~/.apigee"
  roles:
    - { role: apigee-opdk-modules }
  tasks:
    - name: Ensure target folder exists
      file:
        path: "{{ apigee_home }}/data/apigee-mirror/repos/thirdparty/7"
        state: directory
        owner: apigee
        group: apigee

    - name: Create list of actual rpm file names
      find:
        path: '{{ local_apigee_path }}'
        pattern: '*.rpm'
        file_type: file
      register: package_names

    - name: Upload yum packages
      become: true
      copy:
        src: "{{ item.path }}"
        dest: "{{ apigee_home }}/data/apigee-mirror/repos/thirdparty/7"
        owner: apigee
        group: apigee
      with_subelements: "{{ package_names.files }}"

    - name: Yum install
      become: true
      yum:
        name: "{{ apigee_home }}/data/apigee-mirror/repos/thirdparty/7/{{ item.path | basename }}"
        state: present
      with_subelements: "{{ package_names.files }}"

