---
- name: Collect Edge Installation Attributes
  hosts: edge
  tags: ['cache']
  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - { role: apigee-opdk-modules }
    - { role: apigee-opdk-settings-private-address  }
    - { role: apigee-opdk-settings-management-server  }
    - { role: apigee-opdk-settings-ldap  }
    - { role: apigee-opdk-settings-region  }
    - { role: apigee-opdk-settings-cassandra  }
    - { role: apigee-opdk-settings-postgres  }

- name: Download apigee mirror archive
  tags: ['download']
  hosts: "{{ target_hosts }}"
  gather_facts: no
  vars:
    ansible_workspace: "~/.ansible"
    apigee_workspace: "~/.apigee-workspace"
    property_folders:
    - "~/.apigee-secure"
    - "~/.apigee"
  roles:
  - { role: apigee-opdk-setup-default-settings, tags: ['cache'] }
#  - { role: apigee-opdk-os-pre-requisites, tags: ['os'] }
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-setup-apigee-user, tags: ['apigee-user', 'bootstrap'] }
  - { role: apigee-opdk-setup-apigee-user-ownership, tags: ['apigee-user', 'bootstrap'] }
  - { role: apigee-opdk-setup-bootstrap-download-archive, tags: ['download'] }
