---
- name: Playbook to remove a cassandra
  hosts: "{{ target_hosts }}"
  gather_facts: no

  vars:
    nodetool: /opt/apigee/apigee-cassandra/bin/nodetool
    property_folders:
    - '~/.apigee'
    - '~/.apigee-secure'
    component_name: "apigee-cassandra"

  tasks:
  - name: Backup component
    tags: ['backup']
    import_role:
      name: apigee-opdk-backup

  - name: Assert variables exist
    assert:
      that:
      - private_address is defined and private_address | trim | length > 0
      - nodetool is defined and nodetool | trim | length > 0
      msg: "Please provide the missing attribute"

  - name: Decommission cassandra node
    command: "{{ apigee_service }} apigee-cassandra decommission"

  - name: Obtain Nodetool status
    command: "{{ nodetool }} status | grep {{ private_address }}"
    register: nodetool_status

  - name: Obtain node UUID
    set_fact:
      uuid: "{{ register.stdout.split()[-1] }}"

  - name: Remove node that is not a part of the ring
    command: "{{ nodetool }} removenode {{ uuid }}"

  - name: Remove Cassandra
    include_tasks: remove-component.yml
