---
- name: Restart of Planet
  hosts: ds,ms,rmp,qpid,pg
  serial: 1
  strategy: free
  tags: ['restart', 'start']
  vars:
    property_folders:
      - "~/.apigee-secure"
      - "~/.apigee"
  roles:
    - { role: apigee-opdk-modules }
    - { role: apigee-server-restart }
