---
- name: Configure SSH for a remote user
  hosts: '{{ hosts }}'
  become: yes

  vars:
    pubkey: '~/.ssh/id_rsa.pub'

  tasks:
  - block:
    - name: Get current user if remote_user not provided
      shell: whoami
      register: whoami

    - name:  Set remote_user
      set_fact:
        remote_user: "{{ whoami.stdout }}"

    - name: Determine state of public key
      stat:
        path: "{{ pubkey }}"
      register: pubkey_state

    delegate_to: localhost

  - block:
    - name: Assert availability of openssh
      yum:
        name: openssh
        state: present

    - name: Generate SSH keys
      shell: ssh-keygen -b 2048 -t rsa -f {{ pubkey }} -q -N ""
      args:
        creates: "{{ pubkey }}"

    delegate_to: localhost
    when: not pubkey_state.stat.exists

  - name: Assert state of public key
    stat:
      path: "{{ pubkey }}"
    register: pubkey_state

  - name: Copy local public keys to server for user {{ user }}
    authorized_key:
      user: '{{ remote_user }}'
      state: present
      key: "{{ lookup('file', '{{ pubkey }}') }}"
    when: pubkey_state.stat.exists is defined

  - name: Enable root login over SSH
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '(^#)(PermitRootLogin yes)'
      line: '\2'
      backrefs: yes
    notify:
    - Restart SSH service
    when: user == 'root'

  handlers:
  - name: Restart SSH service
    service:
      name: sshd
      state: restarted
